#!/usr/bin/env python3
"""
MCN Full-Stack App Generator - Phase 4
Generate complete applications with MCN backend and React frontend
"""

import os
import json
import argparse
from typing import Dict, List, Any
from pathlib import Path


class MCNAppGenerator:
    def __init__(self):
        self.templates_dir = Path(__file__).parent / "templates"

    def create_app(
        self, app_name: str, template: str = "business", features: List[str] = None
    ):
        """Create a new MCN full-stack application"""
        print(f"Creating MCN app: {app_name}")
        print(f"Template: {template}")

        app_dir = Path(app_name)
        if app_dir.exists():
            print(f"Error: Directory {app_name} already exists")
            return 1

        # Create directory structure
        self._create_directory_structure(app_dir)

        # Generate backend MCN files
        self._generate_backend(app_dir, template, features or [])

        # Generate React frontend
        self._generate_frontend(app_dir, app_name, template)

        # Generate configuration files
        self._generate_config_files(app_dir, app_name)

        print(f"✓ MCN app '{app_name}' created successfully!")
        print(f"\nNext steps:")
        print(f"  cd {app_name}")
        print(f"  npm install")
        print(f"  npm run dev")

        return 0

    def generate_model(self, model_name: str, fields: Dict[str, str]):
        """Generate MCN model with CRUD operations"""
        print(f"Generating model: {model_name}")

        # Generate MCN backend model
        model_mcn = self._generate_model_mcn(model_name, fields)

        # Write to backend directory
        backend_dir = Path("backend")
        if not backend_dir.exists():
            backend_dir.mkdir()

        model_file = backend_dir / f"{model_name.lower()}.mcn"
        with open(model_file, "w") as f:
            f.write(model_mcn)

        print(f"✓ Model {model_name} generated at {model_file}")
        return 0

    def generate_api(self, resource_name: str, crud: bool = True):
        """Generate API endpoints for resource"""
        print(f"Generating API for: {resource_name}")

        api_mcn = self._generate_api_mcn(resource_name, crud)

        # Write to backend directory
        backend_dir = Path("backend")
        if not backend_dir.exists():
            backend_dir.mkdir()

        api_file = backend_dir / f"{resource_name.lower()}_api.mcn"
        with open(api_file, "w") as f:
            f.write(api_mcn)

        print(f"✓ API {resource_name} generated at {api_file}")
        return 0

    def generate_ui(self, component_name: str, model_name: str = None):
        """Generate React UI component"""
        print(f"Generating UI component: {component_name}")

        component_tsx = self._generate_component_tsx(component_name, model_name)

        # Write to frontend directory
        frontend_dir = Path("frontend/src/components")
        if not frontend_dir.exists():
            frontend_dir.mkdir(parents=True)

        component_file = frontend_dir / f"{component_name}.tsx"
        with open(component_file, "w") as f:
            f.write(component_tsx)

        print(f"✓ Component {component_name} generated at {component_file}")
        return 0

    def _create_directory_structure(self, app_dir: Path):
        """Create application directory structure"""
        directories = [
            app_dir,
            app_dir / "backend",
            app_dir / "frontend" / "src" / "components",
            app_dir / "frontend" / "src" / "services",
            app_dir / "frontend" / "src" / "pages",
            app_dir / "frontend" / "public",
            app_dir / "config",
            app_dir / "docs",
        ]

        for directory in directories:
            directory.mkdir(parents=True, exist_ok=True)

    def _generate_backend(self, app_dir: Path, template: str, features: List[str]):
        """Generate MCN backend files"""

        # Main application file
        main_mcn = f"""// {app_dir.name} - MCN Backend
// Generated by MCN App Generator

log "Starting {app_dir.name} backend..."

// Load required packages
use "db"
use "ai"
use "http"

// Initialize database
query("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT, email TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")

// Health check endpoint
var health_check = {{
    "status": "healthy",
    "service": "{app_dir.name}",
    "timestamp": "2025-10-01T10:30:00Z"
}}

// Main application logic
if request_data.action == "health"
    health_check
else if request_data.action == "users"
    var users = query("SELECT * FROM users")
    {{"success": true, "data": users}}
else
    {{"success": false, "error": "Unknown action"}}
"""

        with open(app_dir / "backend" / "main.mcn", "w") as f:
            f.write(main_mcn)

        # Authentication if requested
        if "auth" in features:
            auth_mcn = """// Authentication module
var user_email = request_data.email
var user_password = request_data.password

if request_data.action == "login"
    var user = query("SELECT * FROM users WHERE email = ?", (user_email,))
    if user
        {"success": true, "token": "jwt_token_here", "user": user[0]}
    else
        {"success": false, "error": "Invalid credentials"}
"""
            with open(app_dir / "backend" / "auth.mcn", "w") as f:
                f.write(auth_mcn)

    def _generate_frontend(self, app_dir: Path, app_name: str, template: str):
        """Generate React frontend"""

        # Package.json
        package_json = {
            "name": f"{app_name}-frontend",
            "version": "1.0.0",
            "private": True,
            "dependencies": {
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-scripts": "5.0.1",
                "typescript": "^4.9.5",
                "@types/react": "^18.0.28",
                "@types/react-dom": "^18.0.11",
                "axios": "^1.3.4",
                "tailwindcss": "^3.2.7",
            },
            "scripts": {
                "start": "react-scripts start",
                "build": "react-scripts build",
                "test": "react-scripts test",
                "eject": "react-scripts eject",
            },
        }

        with open(app_dir / "frontend" / "package.json", "w") as f:
            json.dump(package_json, f, indent=2)

        # Main App component
        app_tsx = f"""import React from 'react';
import './App.css';
import {{ MCNProvider }} from './services/mcn-client';

function App() {{
  return (
    <MCNProvider endpoint="http://localhost:8000">
      <div className="App">
        <header className="App-header">
          <h1>{app_name}</h1>
          <p>Built with MCN Full-Stack Framework</p>
        </header>
        <main>
          <UserList />
        </main>
      </div>
    </MCNProvider>
  );
}}

function UserList() {{
  const [users, setUsers] = React.useState([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {{
    fetch('/api/main', {{
      method: 'POST',
      headers: {{ 'Content-Type': 'application/json' }},
      body: JSON.stringify({{ action: 'users' }})
    }})
    .then(res => res.json())
    .then(data => {{
      if (data.success) {{
        setUsers(data.data);
      }}
      setLoading(false);
    }});
  }}, []);

  if (loading) return <div>Loading...</div>;

  return (
    <div className="user-list">
      <h2>Users</h2>
      {{users.map(user => (
        <div key={{user.id}} className="user-card">
          <h3>{{user.name}}</h3>
          <p>{{user.email}}</p>
        </div>
      ))}}
    </div>
  );
}}

export default App;
"""

        with open(app_dir / "frontend" / "src" / "App.tsx", "w") as f:
            f.write(app_tsx)

        # MCN Client service
        mcn_client_tsx = """import React, {{ createContext, useContext }} from 'react';
import axios from 'axios';

interface MCNContextType {{
  endpoint: string;
  call: (action: string, data?: any) => Promise<any>;
}}

const MCNContext = createContext<MCNContextType | null>(null);

export function MCNProvider({{ children, endpoint }}: {{ children: React.ReactNode, endpoint: string }}) {{
  const call = async (action: string, data: any = {{}}) => {{
    const response = await axios.post(`${{endpoint}}/api/main`, {{
      action,
      ...data
    }});
    return response.data;
  }};

  return (
    <MCNContext.Provider value={{{{ endpoint, call }}}}>
      {{children}}
    </MCNContext.Provider>
  );
}}

export function useMCN() {{
  const context = useContext(MCNContext);
  if (!context) {{
    throw new Error('useMCN must be used within MCNProvider');
  }}
  return context;
}}
"""

        with open(
            app_dir / "frontend" / "src" / "services" / "mcn-client.tsx", "w"
        ) as f:
            f.write(mcn_client_tsx)

    def _generate_config_files(self, app_dir: Path, app_name: str):
        """Generate configuration files"""

        # Docker Compose for development
        docker_compose = f"""version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MCN_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
"""

        with open(app_dir / "docker-compose.yml", "w") as f:
            f.write(docker_compose)

        # README
        readme = f"""# {app_name}

MCN Full-Stack Application generated by MCN App Generator.

## Quick Start

### Development
```bash
# Install frontend dependencies
cd frontend && npm install

# Start development servers
docker-compose up

# Or run separately:
# Backend: python mcn_cli.py backend/main.mcn --serve
# Frontend: cd frontend && npm start
```

### Deployment
```bash
# Deploy to MCN Cloud
mcn-cloud deploy backend/main.mcn --env production

# Build frontend for production
cd frontend && npm run build
```

## Structure

- `backend/` - MCN backend scripts
- `frontend/` - React frontend application
- `config/` - Configuration files
- `docs/` - Documentation

## Features

- MCN backend with database integration
- React frontend with TypeScript
- Docker development environment
- MCN Cloud deployment ready
"""

        with open(app_dir / "README.md", "w") as f:
            f.write(readme)

    def _generate_model_mcn(self, model_name: str, fields: Dict[str, str]) -> str:
        """Generate MCN model file"""

        # Create table SQL
        field_definitions = []
        for field_name, field_type in fields.items():
            sql_type = {
                "string": "TEXT",
                "number": "INTEGER",
                "float": "REAL",
                "boolean": "BOOLEAN",
                "date": "TIMESTAMP",
            }.get(field_type, "TEXT")
            field_definitions.append(f"{field_name} {sql_type}")

        create_sql = f"CREATE TABLE IF NOT EXISTS {model_name.lower()}s (id INTEGER PRIMARY KEY AUTOINCREMENT, {', '.join(field_definitions)}, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"

        return f"""// {model_name} Model - Generated by MCN
log "Initializing {model_name} model..."

// Create table
query("{create_sql}")

// CRUD Operations
var action = request_data.action
var {model_name.lower()}_id = request_data.id

if action == "create"
    // Create new {model_name.lower()}
    {self._generate_create_logic(model_name, fields)}

else if action == "read"
    // Read {model_name.lower()}(s)
    if {model_name.lower()}_id
        var result = query("SELECT * FROM {model_name.lower()}s WHERE id = ?", ({model_name.lower()}_id,))
        {{"success": true, "data": result[0] or null}}
    else
        var results = query("SELECT * FROM {model_name.lower()}s ORDER BY created_at DESC")
        {{"success": true, "data": results}}

else if action == "update"
    // Update {model_name.lower()}
    {self._generate_update_logic(model_name, fields)}

else if action == "delete"
    // Delete {model_name.lower()}
    query("DELETE FROM {model_name.lower()}s WHERE id = ?", ({model_name.lower()}_id,))
    {{"success": true, "message": "{model_name} deleted"}}

else
    {{"success": false, "error": "Unknown action"}}
"""

    def _generate_create_logic(self, model_name: str, fields: Dict[str, str]) -> str:
        field_names = list(fields.keys())
        field_placeholders = ", ".join(["?" for _ in field_names])
        field_values = ", ".join([f"request_data.{field}" for field in field_names])

        return f"""var field_values = ({field_values})
    query("INSERT INTO {model_name.lower()}s ({', '.join(field_names)}) VALUES ({field_placeholders})", field_values)
    {{"success": true, "message": "{model_name} created"}}"""

    def _generate_update_logic(self, model_name: str, fields: Dict[str, str]) -> str:
        set_clauses = [f"{field} = ?" for field in fields.keys()]
        field_values = ", ".join([f"request_data.{field}" for field in fields.keys()])

        return f"""var field_values = ({field_values}, {model_name.lower()}_id)
    query("UPDATE {model_name.lower()}s SET {', '.join(set_clauses)} WHERE id = ?", field_values)
    {{"success": true, "message": "{model_name} updated"}}"""

    def _generate_api_mcn(self, resource_name: str, crud: bool) -> str:
        """Generate API MCN file"""
        return f'''// {resource_name} API - Generated by MCN
log "Processing {resource_name} API request..."

var action = request_data.action or "list"
var {resource_name.lower()}_id = request_data.id

// Route to appropriate handler
if action == "list"
    var items = query("SELECT * FROM {resource_name.lower()}s ORDER BY created_at DESC")
    {{"success": true, "data": items}}

else if action == "get" and {resource_name.lower()}_id
    var item = query("SELECT * FROM {resource_name.lower()}s WHERE id = ?", ({resource_name.lower()}_id,))
    if item
        {{"success": true, "data": item[0]}}
    else
        {{"success": false, "error": "{resource_name} not found"}}

{"else if action == \"create\"" if crud else ""}
{"    // Create logic here" if crud else ""}
{"    {\"success\": true, \"message\": \"Created\"}" if crud else ""}

else
    {{"success": false, "error": "Invalid action"}}
'''

    def _generate_component_tsx(
        self, component_name: str, model_name: str = None
    ) -> str:
        """Generate React component"""
        return f"""import React from 'react';
import {{ useMCN }} from '../services/mcn-client';

interface {component_name}Props {{
  // Add props here
}}

export function {component_name}(props: {component_name}Props) {{
  const mcn = useMCN();
  const [data, setData] = React.useState([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {{
    const fetchData = async () => {{
      try {{
        const result = await mcn.call('list');
        if (result.success) {{
          setData(result.data);
        }}
      }} catch (error) {{
        console.error('Error fetching data:', error);
      }} finally {{
        setLoading(false);
      }}
    }};

    fetchData();
  }}, [mcn]);

  if (loading) {{
    return <div className="loading">Loading...</div>;
  }}

  return (
    <div className="{component_name.lower()}">
      <h2>{component_name}</h2>
      {{data.map((item: any) => (
        <div key={{item.id}} className="item">
          {{/* Render item data here */}}
          <pre>{{JSON.stringify(item, null, 2)}}</pre>
        </div>
      ))}}
    </div>
  );
}}

export default {component_name};
"""


def main():
    parser = argparse.ArgumentParser(description="MCN Full-Stack App Generator")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # New app command
    new_parser = subparsers.add_parser("new", help="Create new MCN app")
    new_parser.add_argument("name", help="Application name")
    new_parser.add_argument(
        "--template", default="business", help="App template (default: business)"
    )
    new_parser.add_argument(
        "--features", nargs="*", help="Additional features (auth, analytics, etc.)"
    )

    # Generate model command
    model_parser = subparsers.add_parser("generate-model", help="Generate model")
    model_parser.add_argument("name", help="Model name")
    model_parser.add_argument(
        "--fields", help="Fields in format name:type,email:string,age:number"
    )

    # Generate API command
    api_parser = subparsers.add_parser("generate-api", help="Generate API")
    api_parser.add_argument("name", help="Resource name")
    api_parser.add_argument(
        "--crud", action="store_true", help="Include CRUD operations"
    )

    # Generate UI command
    ui_parser = subparsers.add_parser("generate-ui", help="Generate UI component")
    ui_parser.add_argument("name", help="Component name")
    ui_parser.add_argument("--model", help="Associated model name")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    generator = MCNAppGenerator()

    if args.command == "new":
        return generator.create_app(args.name, args.template, args.features)
    elif args.command == "generate-model":
        fields = {}
        if args.fields:
            for field_def in args.fields.split(","):
                name, field_type = field_def.split(":")
                fields[name] = field_type
        return generator.generate_model(args.name, fields)
    elif args.command == "generate-api":
        return generator.generate_api(args.name, args.crud)
    elif args.command == "generate-ui":
        return generator.generate_ui(args.name, args.model)
    else:
        print(f"Unknown command: {args.command}")
        return 1


if __name__ == "__main__":
    exit(main())
