#!/usr/bin/env python3
"""
MCN Full-Stack App Generator - Phase 4
Generate complete applications with MCN backend and React frontend
"""

import os
import json
import argparse
from typing import Dict, List, Any
from pathlib import Path


class MCNAppGenerator:
    def __init__(self):
        self.templates_dir = Path(__file__).parent / "templates"

    def create_app(
        self, app_name: str, template: str = "business", features: List[str] = None
    ):
        """Create a new MCN full-stack application"""
        print(f"Creating MCN app: {app_name}")
        print(f"Template: {template}")

        app_dir = Path(app_name)
        if app_dir.exists():
            print(f"Error: Directory {app_name} already exists")
            return 1

        # Create directory structure
        self._create_directory_structure(app_dir)

        # Generate backend MCN files
        self._generate_backend(app_dir, template, features or [])

        # Generate React frontend
        self._generate_frontend(app_dir, app_name, template)

        # Generate configuration files
        self._generate_config_files(app_dir, app_name)

        print(f"SUCCESS MCN app '{app_name}' created successfully!")
        print(f"\nNext steps:")
        print(f"  cd {app_name}")
        print(f"  npm install")
        print(f"  npm run dev")

        return 0

    def generate_model(self, model_name: str, fields: Dict[str, str]):
        """Generate MCN model with CRUD operations"""
        print(f"Generating model: {model_name}")

        # Generate MCN backend model
        model_mcn = self._generate_model_mcn(model_name, fields)

        # Write to backend directory
        backend_dir = Path("backend")
        if not backend_dir.exists():
            backend_dir.mkdir()

        model_file = backend_dir / f"{model_name.lower()}.mcn"
        with open(model_file, "w") as f:
            f.write(model_mcn)

        print(f"SUCCESS Model {model_name} generated at {model_file}")
        return 0

    def generate_api(self, resource_name: str, crud: bool = True):
        """Generate API endpoints for resource"""
        print(f"Generating API for: {resource_name}")

        api_mcn = self._generate_api_mcn(resource_name, crud)

        # Write to backend directory
        backend_dir = Path("backend")
        if not backend_dir.exists():
            backend_dir.mkdir()

        api_file = backend_dir / f"{resource_name.lower()}_api.mcn"
        with open(api_file, "w") as f:
            f.write(api_mcn)

        print(f"SUCCESS API {resource_name} generated at {api_file}")
        return 0

    def generate_ui(self, component_name: str, model_name: str = None):
        """Generate React UI component"""
        print(f"Generating UI component: {component_name}")

        component_tsx = self._generate_component_tsx(component_name, model_name)

        # Write to frontend directory
        frontend_dir = Path("frontend/src/components")
        if not frontend_dir.exists():
            frontend_dir.mkdir(parents=True)

        component_file = frontend_dir / f"{component_name}.tsx"
        with open(component_file, "w") as f:
            f.write(component_tsx)

        print(f"SUCCESS Component {component_name} generated at {component_file}")
        return 0

    def _create_directory_structure(self, app_dir: Path):
        """Create application directory structure"""
        directories = [
            app_dir,
            app_dir / "backend",
            app_dir / "frontend" / "src" / "components",
            app_dir / "frontend" / "src" / "services",
            app_dir / "frontend" / "src" / "pages",
            app_dir / "frontend" / "public",
            app_dir / "config",
            app_dir / "docs",
        ]

        for directory in directories:
            directory.mkdir(parents=True, exist_ok=True)

    def _generate_backend(self, app_dir: Path, template: str, features: List[str]):
        """Generate MCN backend files with dynamic systems"""

        # Main application file with real functionality
        main_mcn = f"""// {app_dir.name} - MCN Backend
// Generated by MCN App Generator with Dynamic Systems

log("Starting {app_dir.name} backend...")

// Load dynamic packages
use "db"
use "ai"
use "http"
use "analytics"
use "auth"

// Initialize database with real tables
query("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT, email TEXT, password_hash TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
query("CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id INTEGER, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
query("CREATE TABLE IF NOT EXISTS app_data (id INTEGER PRIMARY KEY, key TEXT, value TEXT, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")

// Insert sample data if empty
var user_count = query("SELECT COUNT(*) as count FROM users")
if user_count[0].count == 0
    query("INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)", ("Admin User", "admin@{app_dir.name.lower()}.com", "hashed_password_123"))
    query("INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)", ("Demo User", "demo@{app_dir.name.lower()}.com", "hashed_password_456"))
    log("Sample users created")

// Real API endpoints
var action = request_data.action or "health"
var user_id = request_data.user_id
var page = request_data.page or 1
var limit = request_data.limit or 10

if action == "health"
    // Health check with real system info
    var db_status = query("SELECT 1 as test")
    {{
        "status": "healthy",
        "service": "{app_dir.name}",
        "timestamp": now(),
        "database": db_status.length > 0 ? "connected" : "disconnected",
        "version": "1.0.0"
    }}

else if action == "users"
    // Get users with pagination
    var offset = (page - 1) * limit
    var users = query("SELECT id, name, email, created_at FROM users ORDER BY created_at DESC LIMIT ? OFFSET ?", (limit, offset))
    var total = query("SELECT COUNT(*) as count FROM users")
    {{
        "success": true,
        "data": users,
        "pagination": {{
            "page": page,
            "limit": limit,
            "total": total[0].count
        }}
    }}

else if action == "user_detail" and user_id
    // Get specific user
    var user = query("SELECT id, name, email, created_at FROM users WHERE id = ?", (user_id,))
    if user.length > 0
        {{"success": true, "data": user[0]}}
    else
        {{"success": false, "error": "User not found"}}

else if action == "dashboard_data"
    // Dashboard metrics with real data
    var user_count = query("SELECT COUNT(*) as count FROM users")
    var recent_users = query("SELECT COUNT(*) as count FROM users WHERE created_at > datetime('now', '-7 days')")
    
    // Track analytics
    track("dashboard_view", {{"timestamp": now()}})
    
    {{
        "success": true,
        "data": {{
            "total_users": user_count[0].count,
            "new_users_week": recent_users[0].count,
            "system_status": "operational",
            "last_updated": now()
        }}
    }}

else if action == "create_user"
    // Create new user
    var name = request_data.name
    var email = request_data.email
    var password = request_data.password or "default_password"
    
    if name and email
        query("INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)", (name, email, password))
        track("user_created", {{"email": email}})
        {{"success": true, "message": "User created successfully"}}
    else
        {{"success": false, "error": "Name and email are required"}}

else if action == "analytics"
    // Get analytics data
    var events = get("user_created", 30)
    {{
        "success": true,
        "data": {{
            "events": events,
            "summary": {{"total_events": events.length}}
        }}
    }}

else
    {{"success": false, "error": "Unknown action: " + action}}
"""

        with open(app_dir / "backend" / "main.mcn", "w") as f:
            f.write(main_mcn)

        # Authentication with real functionality
        if "auth" in features:
            auth_mcn = """// Authentication module with real auth
use "auth"
use "db"

var action = request_data.action
var email = request_data.email
var password = request_data.password
var name = request_data.name

if action == "register"
    if name and email and password
        var existing = query("SELECT id FROM users WHERE email = ?", (email,))
        if existing.length > 0
            {{"success": false, "error": "Email already exists"}}
        else
            create_user(name, password, email)
            {{"success": true, "message": "User registered successfully"}}
    else
        {{"success": false, "error": "Name, email and password required"}}

else if action == "login"
    if email and password
        var auth_result = authenticate(email, password)
        if auth_result.success
            track("user_login", {{"user_id": auth_result.user.id}})
            auth_result
        else
            {{"success": false, "error": "Invalid credentials"}}
    else
        {{"success": false, "error": "Email and password required"}}

else if action == "logout"
    var token = request_data.token
    if token
        // In real implementation, invalidate token
        {{"success": true, "message": "Logged out successfully"}}
    else
        {{"success": false, "error": "Token required"}}

else
    {{"success": false, "error": "Unknown auth action"}}
"""
            with open(app_dir / "backend" / "auth.mcn", "w") as f:
                f.write(auth_mcn)
        
        # API routes file
        api_mcn = f"""// API Routes for {app_dir.name}
use "db"
use "http"

// CORS headers for frontend
var cors_headers = {{
    "Access-Control-Allow-Origin": "http://localhost:3000",
    "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization"
}}

// Handle preflight requests
if request_data.method == "OPTIONS"
    {{"success": true, "headers": cors_headers}}

// Route requests based on endpoint
var endpoint = request_data.endpoint or "main"

if endpoint == "users"
    // User management endpoints
    var result = query("SELECT id, name, email, created_at FROM users ORDER BY created_at DESC")
    {{"success": true, "data": result, "headers": cors_headers}}

else if endpoint == "dashboard"
    // Dashboard data endpoint
    var metrics = {{
        "users": query("SELECT COUNT(*) as count FROM users")[0].count,
        "active_sessions": 0,
        "system_health": "good"
    }}
    {{"success": true, "data": metrics, "headers": cors_headers}}

else
    // Default main endpoint
    {{"success": true, "message": "API is working", "headers": cors_headers}}
"""
        
        with open(app_dir / "backend" / "api.mcn", "w") as f:
            f.write(api_mcn)

    def _generate_frontend(self, app_dir: Path, app_name: str, template: str):
        """Generate React frontend"""

        # Package.json
        package_json = {
            "name": f"{app_name}-frontend",
            "version": "1.0.0",
            "private": True,
            "dependencies": {
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-router-dom": "^6.20.1",
                "react-scripts": "5.0.1",
                "typescript": "^5.3.3",
                "@types/react": "^18.2.45",
                "@types/react-dom": "^18.2.18",
                "axios": "^1.6.2",
                "tailwindcss": "^3.3.6",
                "@radix-ui/react-slot": "^1.0.2",
                "@radix-ui/react-dialog": "^1.0.5",
                "class-variance-authority": "^0.7.0",
                "clsx": "^2.0.0",
                "tailwind-merge": "^2.0.0",
                "lucide-react": "^0.294.0"
            },
            "scripts": {
                "start": "react-scripts start",
                "build": "react-scripts build",
                "test": "react-scripts test",
                "eject": "react-scripts eject",
            },
            "devDependencies": {
                "@types/node": "^20.10.5",
                "autoprefixer": "^10.4.16",
                "postcss": "^8.4.32",
                "tailwindcss-animate": "^1.0.7"
            }
        }

        with open(app_dir / "frontend" / "package.json", "w") as f:
            json.dump(package_json, f, indent=2)

        # Enhanced App component with ShadCN UI
        app_tsx = f"""import React from 'react';
import {{ BrowserRouter as Router, Routes, Route, Link }} from 'react-router-dom';
import {{ MCNProvider }} from './services/mcn-client';
import {{ Button }} from './components/ui/button';
import {{ Card, CardContent, CardDescription, CardHeader, CardTitle }} from './components/ui/card';
import {{ Table, TableBody, TableCell, TableHead, TableHeader, TableRow }} from './components/ui/table';
import './styles/index.css';

function App() {{
  return (
    <MCNProvider endpoint="http://localhost:8000">
      <Router>
        <div className="min-h-screen bg-background">
          <nav className="border-b">
            <div className="container mx-auto px-4 py-4">
              <div className="flex justify-between items-center">
                <h1 className="text-2xl font-bold">{app_name}</h1>
                <div className="space-x-4">
                  <Link to="/">
                    <Button variant="ghost">Dashboard</Button>
                  </Link>
                  <Link to="/users">
                    <Button variant="ghost">Users</Button>
                  </Link>
                </div>
              </div>
            </div>
          </nav>
          
          <main className="container mx-auto px-4 py-8">
            <Routes>
              <Route path="/" element={{<Dashboard />}} />
              <Route path="/users" element={{<UserList />}} />
            </Routes>
          </main>
        </div>
      </Router>
    </MCNProvider>
  );
}}

function Dashboard() {{
  const [metrics, setMetrics] = React.useState(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {{
    fetch('/api/main', {{
      method: 'POST',
      headers: {{ 'Content-Type': 'application/json' }},
      body: JSON.stringify({{ action: 'dashboard_data' }})
    }})
    .then(res => res.json())
    .then(data => {{
      if (data.success) {{
        setMetrics(data.data);
      }}
      setLoading(false);
    }});
  }}, []);

  if (loading) return <div className="loading">Loading dashboard...</div>;

  return (
    <div className="space-y-6">
      <div className="dashboard-header">
        <h2 className="dashboard-title">Dashboard</h2>
        <Button onClick={{() => window.location.reload()}}>Refresh</Button>
      </div>
      
      <div className="metrics-row">
        <Card className="metric-card">
          <CardHeader>
            <CardTitle>Total Users</CardTitle>
            <CardDescription>Registered users</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="metric-value">{{metrics?.total_users || 0}}</div>
          </CardContent>
        </Card>
        
        <Card className="metric-card">
          <CardHeader>
            <CardTitle>New This Week</CardTitle>
            <CardDescription>Users registered this week</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="metric-value">{{metrics?.new_users_week || 0}}</div>
          </CardContent>
        </Card>
        
        <Card className="metric-card">
          <CardHeader>
            <CardTitle>System Status</CardTitle>
            <CardDescription>Current system health</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="metric-value text-green-600">{{metrics?.system_status || 'Unknown'}}</div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}}

function UserList() {{
  const [users, setUsers] = React.useState([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {{
    fetch('/api/main', {{
      method: 'POST',
      headers: {{ 'Content-Type': 'application/json' }},
      body: JSON.stringify({{ action: 'users' }})
    }})
    .then(res => res.json())
    .then(data => {{
      if (data.success) {{
        setUsers(data.data);
      }}
      setLoading(false);
    }});
  }}, []);

  if (loading) return <div className="loading">Loading users...</div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-3xl font-bold">Users</h2>
        <Button>Add User</Button>
      </div>
      
      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>ID</TableHead>
              <TableHead>Name</TableHead>
              <TableHead>Email</TableHead>
              <TableHead>Created</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {{users.map(user => (
              <TableRow key={{user.id}}>
                <TableCell>{{user.id}}</TableCell>
                <TableCell className="font-medium">{{user.name}}</TableCell>
                <TableCell>{{user.email}}</TableCell>
                <TableCell>{{new Date(user.created_at).toLocaleDateString()}}</TableCell>
              </TableRow>
            ))}}
          </TableBody>
        </Table>
      </Card>
    </div>
  );
}}

export default App;
"""

        with open(app_dir / "frontend" / "src" / "App.tsx", "w") as f:
            f.write(app_tsx)
        
        # Generate components.json for ShadCN
        components_json = {
            "$schema": "https://ui.shadcn.com/schema.json",
            "style": "default",
            "rsc": False,
            "tsx": True,
            "tailwind": {
                "config": "tailwind.config.js",
                "css": "src/styles/index.css",
                "baseColor": "slate",
                "cssVariables": True
            },
            "aliases": {
                "components": "@/components",
                "utils": "@/utils"
            }
        }
        
        with open(app_dir / "frontend" / "components.json", "w") as f:
            json.dump(components_json, f, indent=2)

        # MCN Client service
        mcn_client_tsx = """import React, {{ createContext, useContext }} from 'react';
import axios from 'axios';

interface MCNContextType {{
  endpoint: string;
  call: (action: string, data?: any) => Promise<any>;
}}

const MCNContext = createContext<MCNContextType | null>(null);

export function MCNProvider({{ children, endpoint }}: {{ children: React.ReactNode, endpoint: string }}) {{
  const call = async (action: string, data: any = {{}}) => {{
    const response = await axios.post(`${{endpoint}}/api/main`, {{
      action,
      ...data
    }});
    return response.data;
  }};

  return (
    <MCNContext.Provider value={{{{ endpoint, call }}}}>
      {{children}}
    </MCNContext.Provider>
  );
}}

export function useMCN() {{
  const context = useContext(MCNContext);
  if (!context) {{
    throw new Error('useMCN must be used within MCNProvider');
  }}
  return context;
}}
"""

        with open(
            app_dir / "frontend" / "src" / "services" / "mcn-client.tsx", "w"
        ) as f:
            f.write(mcn_client_tsx)

    def _generate_config_files(self, app_dir: Path, app_name: str):
        """Generate configuration files"""

        # Docker Compose for development
        docker_compose = f"""version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MCN_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
"""

        with open(app_dir / "docker-compose.yml", "w") as f:
            f.write(docker_compose)

        # README
        readme = f"""# {app_name}

MCN Full-Stack Application generated by MCN App Generator.

## Quick Start

### Development
```bash
# Install frontend dependencies
cd frontend && npm install

# Start development servers
docker-compose up

# Or run separately:
# Backend: python mcn_cli.py backend/main.mcn --serve
# Frontend: cd frontend && npm start
```

### Deployment
```bash
# Deploy to MCN Cloud
mcn-cloud deploy backend/main.mcn --env production

# Build frontend for production
cd frontend && npm run build
```

## Structure

- `backend/` - MCN backend scripts
- `frontend/` - React frontend application
- `config/` - Configuration files
- `docs/` - Documentation

## Features

- MCN backend with database integration
- React frontend with TypeScript
- Docker development environment
- MCN Cloud deployment ready
"""

        with open(app_dir / "README.md", "w") as f:
            f.write(readme)

    def _generate_model_mcn(self, model_name: str, fields: Dict[str, str]) -> str:
        """Generate MCN model file"""

        # Create table SQL
        field_definitions = []
        for field_name, field_type in fields.items():
            sql_type = {
                "string": "TEXT",
                "number": "INTEGER",
                "float": "REAL",
                "boolean": "BOOLEAN",
                "date": "TIMESTAMP",
            }.get(field_type, "TEXT")
            field_definitions.append(f"{field_name} {sql_type}")

        create_sql = f"CREATE TABLE IF NOT EXISTS {model_name.lower()}s (id INTEGER PRIMARY KEY AUTOINCREMENT, {', '.join(field_definitions)}, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"

        return f"""// {model_name} Model - Generated by MCN
log "Initializing {model_name} model..."

// Create table
query("{create_sql}")

// CRUD Operations
var action = request_data.action
var {model_name.lower()}_id = request_data.id

if action == "create"
    // Create new {model_name.lower()}
    {self._generate_create_logic(model_name, fields)}

else if action == "read"
    // Read {model_name.lower()}(s)
    if {model_name.lower()}_id
        var result = query("SELECT * FROM {model_name.lower()}s WHERE id = ?", ({model_name.lower()}_id,))
        {{"success": true, "data": result[0] or null}}
    else
        var results = query("SELECT * FROM {model_name.lower()}s ORDER BY created_at DESC")
        {{"success": true, "data": results}}

else if action == "update"
    // Update {model_name.lower()}
    {self._generate_update_logic(model_name, fields)}

else if action == "delete"
    // Delete {model_name.lower()}
    query("DELETE FROM {model_name.lower()}s WHERE id = ?", ({model_name.lower()}_id,))
    {{"success": true, "message": "{model_name} deleted"}}

else
    {{"success": false, "error": "Unknown action"}}
"""

    def _generate_create_logic(self, model_name: str, fields: Dict[str, str]) -> str:
        field_names = list(fields.keys())
        field_placeholders = ", ".join(["?" for _ in field_names])
        field_values = ", ".join([f"request_data.{field}" for field in field_names])

        return f"""var field_values = ({field_values})
    query("INSERT INTO {model_name.lower()}s ({', '.join(field_names)}) VALUES ({field_placeholders})", field_values)
    {{"success": true, "message": "{model_name} created"}}"""

    def _generate_update_logic(self, model_name: str, fields: Dict[str, str]) -> str:
        set_clauses = [f"{field} = ?" for field in fields.keys()]
        field_values = ", ".join([f"request_data.{field}" for field in fields.keys()])

        return f"""var field_values = ({field_values}, {model_name.lower()}_id)
    query("UPDATE {model_name.lower()}s SET {', '.join(set_clauses)} WHERE id = ?", field_values)
    {{"success": true, "message": "{model_name} updated"}}"""

    def _generate_api_mcn(self, resource_name: str, crud: bool) -> str:
        """Generate API MCN file"""
        return f'''// {resource_name} API - Generated by MCN
log "Processing {resource_name} API request..."

var action = request_data.action or "list"
var {resource_name.lower()}_id = request_data.id

// Route to appropriate handler
if action == "list"
    var items = query("SELECT * FROM {resource_name.lower()}s ORDER BY created_at DESC")
    {{"success": true, "data": items}}

else if action == "get" and {resource_name.lower()}_id
    var item = query("SELECT * FROM {resource_name.lower()}s WHERE id = ?", ({resource_name.lower()}_id,))
    if item
        {{"success": true, "data": item[0]}}
    else
        {{"success": false, "error": "{resource_name} not found"}}

{"else if action == \"create\"" if crud else ""}
{"    // Create logic here" if crud else ""}
{"    {\"success\": true, \"message\": \"Created\"}" if crud else ""}

else
    {{"success": false, "error": "Invalid action"}}
'''

    def _generate_component_tsx(
        self, component_name: str, model_name: str = None
    ) -> str:
        """Generate React component"""
        return f"""import React from 'react';
import {{ useMCN }} from '../services/mcn-client';

interface {component_name}Props {{
  // Add props here
}}

export function {component_name}(props: {component_name}Props) {{
  const mcn = useMCN();
  const [data, setData] = React.useState([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {{
    const fetchData = async () => {{
      try {{
        const result = await mcn.call('list');
        if (result.success) {{
          setData(result.data);
        }}
      }} catch (error) {{
        console.error('Error fetching data:', error);
      }} finally {{
        setLoading(false);
      }}
    }};

    fetchData();
  }}, [mcn]);

  if (loading) {{
    return <div className="loading">Loading...</div>;
  }}

  return (
    <div className="{component_name.lower()}">
      <h2>{component_name}</h2>
      {{data.map((item: any) => (
        <div key={{item.id}} className="item">
          {{/* Render item data here */}}
          <pre>{{JSON.stringify(item, null, 2)}}</pre>
        </div>
      ))}}
    </div>
  );
}}

export default {component_name};
"""


def main():
    parser = argparse.ArgumentParser(description="MCN Full-Stack App Generator")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # New app command
    new_parser = subparsers.add_parser("new", help="Create new MCN app")
    new_parser.add_argument("name", help="Application name")
    new_parser.add_argument(
        "--template", default="business", help="App template (default: business)"
    )
    new_parser.add_argument(
        "--features", nargs="*", help="Additional features (auth, analytics, etc.)"
    )

    # Generate model command
    model_parser = subparsers.add_parser("generate-model", help="Generate model")
    model_parser.add_argument("name", help="Model name")
    model_parser.add_argument(
        "--fields", help="Fields in format name:type,email:string,age:number"
    )

    # Generate API command
    api_parser = subparsers.add_parser("generate-api", help="Generate API")
    api_parser.add_argument("name", help="Resource name")
    api_parser.add_argument(
        "--crud", action="store_true", help="Include CRUD operations"
    )

    # Generate UI command
    ui_parser = subparsers.add_parser("generate-ui", help="Generate UI component")
    ui_parser.add_argument("name", help="Component name")
    ui_parser.add_argument("--model", help="Associated model name")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    generator = MCNAppGenerator()

    if args.command == "new":
        return generator.create_app(args.name, args.template, args.features)
    elif args.command == "generate-model":
        fields = {}
        if args.fields:
            for field_def in args.fields.split(","):
                name, field_type = field_def.split(":")
                fields[name] = field_type
        return generator.generate_model(args.name, fields)
    elif args.command == "generate-api":
        return generator.generate_api(args.name, args.crud)
    elif args.command == "generate-ui":
        return generator.generate_ui(args.name, args.model)
    else:
        print(f"Unknown command: {args.command}")
        return 1


if __name__ == "__main__":
    exit(main())
