import React, { useState, useCallback } from "react"
import { api } from "../services/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

export function PublishStudio() {
  const [title, setTitle] = useState("")
  const [category, setCategory] = useState("Coding & Tech")
  const [ai_tool, setAiTool] = useState("Claude 3.5 Sonnet")
  const [prompt_template, setPromptTemplate] = useState("")
  const [description, setDescription] = useState("")
  const [sample_output, setSampleOutput] = useState("")
  const [price, setPrice] = useState(0.0)
  const [author, setAuthor] = useState("CommunityCreator")
  const [tags, setTags] = useState("")
  const [status_msg, setStatusMsg] = useState("")
  const [loading, setLoading] = useState(false)

  const submit = useCallback(async (e?: React.FormEvent) => {
    if (e) e.preventDefault()
    setLoading(true)
    const res = await api.post('/create_prompt', {title: title, category: category, ai_tool: ai_tool, prompt_template: prompt_template, description: description, sample_output: sample_output, price: price, author: author, tags: tags})
    if (res.success) {
      setStatusMsg("Successfully published to Marketplace!")
      setTitle("")
      setPromptTemplate("")
      setDescription("")
      setSampleOutput("")
      setTags("")
    }
    setLoading(false)
  }, [title, category, ai_tool, prompt_template, description, sample_output, price, author, tags, status_msg, loading])

  return (
    <div >
      <Card >
        <CardHeader>
          <h2 className="text-xl font-semibold">{"Publish Prompt to Global Marketplace"}</h2>
        </CardHeader>
        <CardContent className="pt-6">
          <form onSubmit={submit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label htmlFor="title">{"Prompt Title"}</Label>
                <Input value={title} onChange={(e) => setTitle(e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label>{"Category"}</Label>
                <Select value={category} onValueChange={setCategory}>
                  <SelectTrigger><SelectValue placeholder={"Select…"} /></SelectTrigger>
                  <SelectContent>
                    {["Image & Art", "Coding & Tech", "Marketing & SEO", "AI Agents"].map((o: any) => <SelectItem key={String(o)} value={String(o)}>{String(o)}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label>{"Target AI Model"}</Label>
                <Select value={ai_tool} onValueChange={setAiTool}>
                  <SelectTrigger><SelectValue placeholder={"Select…"} /></SelectTrigger>
                  <SelectContent>
                    {["Midjourney v6", "Claude 3.5 Sonnet", "ChatGPT 4o", "Stable Diffusion XL", "Cursor", "DALL-E 3"].map((o: any) => <SelectItem key={String(o)} value={String(o)}>{String(o)}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <Label htmlFor="price">{"Price in USD ($0 for Free/Community)"}</Label>
                <Input value={price} onChange={(e) => setPrice(e.target.value)} type="number" />
              </div>
            </div>
            <div className="space-y-1">
              <Label>{"Prompt Template (use {{variable}} for inputs)"}</Label>
              <Textarea value={prompt_template} onChange={(e) => setPromptTemplate(e.target.value)} />
            </div>
            <div className="space-y-1">
              <Label>{"What makes this prompt effective? (Description)"}</Label>
              <Textarea value={description} onChange={(e) => setDescription(e.target.value)} />
            </div>
            <div className="space-y-1">
              <Label>{"Sample Output Generated by AI"}</Label>
              <Textarea value={sample_output} onChange={(e) => setSampleOutput(e.target.value)} />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label htmlFor="author">{"Creator Handle"}</Label>
                <Input value={author} onChange={(e) => setAuthor(e.target.value)} />
              </div>
              <div className="space-y-1">
                <Label htmlFor="tags">{"Tags (comma separated)"}</Label>
                <Input value={tags} onChange={(e) => setTags(e.target.value)} />
              </div>
            </div>
            <Button variant="default" disabled={loading}>{"Publish to Marketplace"}</Button>
            <div >
              <span>{status_msg}</span>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

export default PublishStudio
